# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: webpack
email: 302656338@qq.com
description: > # webpack and reactjs.
baseurl: "/webpack" # the subpath of your site, e.g. /blog
url: "https://whatthecole.github.io/webpack/" # the base hostname & protocol for your site
twitter_username: null
github_username:  whatthecole

# Build settings
markdown: kramdown
source: app
destination: docs
